export const GET_ALL_MEMBER = "GET_ALL_MEMBER";
export const SINGLE_DELETE_MEMBER = "SINGLE_DELETE_MEMBER";
export const SUBMITING_FORM_VALUE = "SUBMITING_FORM_VALUE";
export const EDIT_MEMBER = "EDIT_MEMBER";
