export const GET_ALL_MEMBER = "GET_ALL_MEMBER";
export const SINGLE_DELETE_MEMBER = "SINGLE_DELETE_MEMBER";
export const EDIT_DATA = "EDIT_DATA";
export const SHOW_EDIT_VALUE_DATA_IN_FORM = "SHOW_EDIT_VALUE_DATA_IN_FORM";
