export const GET_ALL_MEMBER = "GET_ALL_MEMBER";
export const SINGLE_DELETE_MEMBER = "SINGLE_DELETE_MEMBER";
export const SUBMITING_FORM_VALUE = "SUBMITING_FORM_VALUE";
export const EDIT_MEMBER = "EDIT_MEMBER";
export const HANDLE_INPUT_TEXT = "HANDLE_INPUT_TEXT";
export const SET_MEMBER_ID = "SET_MEMBER_ID";
export const GET_MEMBER_BY_ID = "GET_MEMBER_BY_ID";
